### ISSUE TITLE
DataHub CLI Looker ingestion is broken

### ISSUE THREAD

**Issue by LouisTsiattalou** [datahub-project/datahub#12903]
**Describe the bug**
Looker/Lookml ingestion is broken from the CLI. Here's the relevant part of the stack trace:

```
  File ".venv/lib/python3.12/site-packages/datahub/ingestion/source/looker/looker_template_language.py", line 21, in <module>
    from datahub.ingestion.source.looker.looker_liquid_tag import (
  File ".venv/lib/python3.12/site-packages/datahub/ingestion/source/looker/looker_liquid_tag.py", line 6, in <module>
    from liquid.context import Context
ImportError: cannot import name 'Context' from 'liquid.context' (.venv/lib/python3.12/site-packages/liquid/context.py). Did you mean: 'context'?
```

which downstream raises:

```
datahub.ingestion.run.pipeline.PipelineInitError: Failed to find a registered source for type looker: looker is disabled due to an error in initialization
```

**To Reproduce**
Ingest any Looker / Lookml recipe using `datahub ingest -c <recipe.yaml>`

**Fix**
Fixed by pinning python-liquid to 1.13.0; they published their v2 with breaking changes two days ago.

**Comment by mikesimard** [comment]
Just an FYI, I've got the same error on the UI Ingester. 

` File "/tmp/datahub/ingest/venv-looker-48492ddf5c148a4c/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 80, in _add_init_error_context
    raise PipelineInitError(f"Failed to {step}: {e}") from e
datahub.ingestion.run.pipeline.PipelineInitError: Failed to find a registered source for type looker: looker is disabled due to an error in initialization`

**Comment by hsheth2** [comment]
This was fixed by https://github.com/datahub-project/datahub/pull/12896 last week.

Pin `python-liquid < 2`, or use acryl-datahub v1.0.0.1rc1 or newer.

**Comment by lkchao-majority** [comment]
Hi @hsheth2, I couldn’t find the release you mentioned — the latest release candidate appears to be from before your PR was merged.
Would it be possible to create a new one? Our integration is currently broken after migrating to the latest DataHub version, as it is no longer using a fixed package set in the ingestion image. Thanks!

**Comment by sg-samirine** [comment]
Hello @hsheth2 
That's true that my looker sink was working fine earlier but started failing with new release for looker initiation. what version of datahub solved this problem? 

from liquid.context import Context
ImportError: cannot import name 'Context' from 'liquid.context'

**Comment by hsheth2** [comment]
We release the CLI more frequently than we do the backend/server. You can see the releases here https://pypi.org/project/acryl-datahub/

In the UI, you can set what CLI version to use for ingestion https://datahubproject.io/docs/ui-ingestion/#advanced-ingestion-configs

**Comment by sg-samirine** [comment]
@hsheth2  i did manually update CLI to latest version but still remains same. when i am checking the pip show acryl-datahub it shows latest version 1.0.0.2

But issue remains same and do i need to restart any ingestion service in order to use latest CLI?

  File "/tmp/datahub/ingest/venv-lookml-f9103e0adae041e3/lib/python3.10/site-packages/datahub/ingestion/source/looker/looker_liquid_tag.py", line 6, in <module>
    from liquid.context import Context
ImportError: cannot import name 'Context' from 'liquid.context' (/tmp/datahub/ingest/venv-lookml-f9103e0adae041e3/lib/python3.10/site-packages/liquid/context.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/datahub/ingest/venv-lookml-f9103e0adae041e3/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 138, in _add_init_error_context
    yield
  File "/tmp/datahub/ingest/venv-lookml-f9103e0adae041e3/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 289, in __init__
    source_class = source_registry.get(self.source_type)
  File "/tmp/datahub/ingest/venv-lookml-f9103e0adae041e3/lib/python3.10/site-packages/datahub/ingestion/api/registry.py", line 182, in get
    raise ConfigurationError(
datahub.configuration.common.ConfigurationError: lookml is disabled due to an error in initialization

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/datahub/ingest/venv-lookml-f9103e0adae041e3/lib/python3.10/site-packages/datahub/entrypoints.py", line 231, in main

**Comment by hsheth2** [comment]
@sg-samirine please post the full logs from the ingestion

**Comment by sg-samirine** [comment]
@hsheth2  i resolved the issue with new CLI 1.0.0.2. Thank you.
