### ISSUE TITLE
Quick start : throwing error Received error 500 from server for URI http://datahub-gms:8080/datasets 

### ISSUE THREAD

**Issue by fr-ashikaumagiliya** [datahub-project/datahub#2014]
**Describe the bug**
Followed the Quick Start guides. Ingested sample data as well.
No data new data was available in the Datahub UI.

Throws following errors:

> datahub-frontend        | 09:33:14 [application-akka.actor.default-dispatcher-24] ERROR application - Failed in documents search.
> datahub-frontend        | com.linkedin.restli.client.RestLiResponseException: com.linkedin.restli.client.RestLiResponseException: Response status 500, serviceErrorMessage: INTERNAL SERVER ERROR
> datahub-frontend        | 	at com.linkedin.restli.internal.client.ExceptionUtil.wrapThrowable(ExceptionUtil.java:130)
> datahub-frontend        | 	at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponseImpl(ResponseFutureImpl.java:130)
> .
> .
> datahub-frontend        | Caused by: com.linkedin.restli.client.RestLiResponseException: RestException{_response=RestResponse[headers={content-length=11045, Date=Thu, 26 Nov 2020 09:33:14 GMT, Server=Jetty(9.4.20.v20190813), X-RestLi-Error-Response=true, X-RestLi-Protocol-Version=2.0.0},cookies=[],status=500,entityLength=11045]}
> datahub-frontend        | 	at com.linkedin.restli.internal.client.ExceptionUtil.exceptionForThrowable(ExceptionUtil.java:102)
> datahub-frontend        | 	at com.linkedin.restli.client.RestLiCallbackAdapter.convertError(RestLiCallbackAdapter.java:66)
> datahub-frontend        | 	at com.linkedin.common.callback.CallbackAdapter.onError(CallbackAdapter.java:86)
> datahub-frontend        | 	at com.linkedin.r2.message.timing.TimingCallback.onError(TimingCallback.java:81)
> datahub-frontend        | 	at com.linkedin.r2.transport.common.bridge.client.TransportCallbackAdapter.onResponse(TransportCallbackAdapter.java:47)
> datahub-frontend        | 	at com.linkedin.r2.filter.transport.FilterChainClient.lambda$createWrappedClientTimingCallback$0(FilterChainClient.java:113)
> datahub-frontend        | 	at com.linkedin.r2.filter.transport.ResponseFilter.onRestError(ResponseFilter.java:79)
> datahub-frontend        | 	at com.linkedin.r2.filter.TimedRestFilter.onRestError(TimedRestFilter.java:92)
> datahub-frontend        | 	at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:166)
> datahub-frontend        | 	at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:132)
> datahub-frontend        | 	at com.linkedin.r2.filter.FilterChainIterator.onError(FilterChainIterator.java:101)
> datahub-frontend        | 	at com.linkedin.r2.filter.TimedNextFilter.onError(TimedNextFilter.java:48)
> datahub-frontend        | 	at com.linkedin.r2.filter.message.rest.RestFilter.onRestError(RestFilter.java:84)
> datahub-frontend        | 	at com.linkedin.r2.filter.TimedRestFilter.onRestError(TimedRestFilter.java:92)
> datahub-frontend        | 	at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:166)
> datahub-frontend        | 	at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:132)
> datahub-frontend        | 	at com.linkedin.r2.filter.FilterChainIterator.onError(FilterChainIterator.java:101)
> datahub-frontend        | 	at com.linkedin.r2.filter.TimedNextFilter.onError(TimedNextFilter.java:48)
> datahub-frontend        | 	at com.linkedin.r2.filter.message.rest.RestFilter.onRestError(RestFilter.java:84)
> datahub-frontend        | 	at com.linkedin.r2.filter.TimedRestFilter.onRestError(TimedRestFilter.java:92)
> datahub-frontend        | 	at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:166)
> datahub-frontend        | 	at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:132)
> datahub-frontend        | 	at com.linkedin.r2.filter.FilterChainIterator.onError(FilterChainIterator.java:101)
> datahub-frontend        | 	at com.linkedin.r2.filter.TimedNextFilter.onError(TimedNextFilter.java:48)
> datahub-frontend        | 	at com.linkedin.r2.filter.message.rest.RestFilter.onRestError(RestFilter.java:84)
> datahub-frontend        | 	at com.linkedin.r2.filter.TimedRestFilter.onRestError(TimedRestFilter.java:92)
> datahub-frontend        | 	at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:166)
> datahub-frontend        | 	at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:132)
> datahub-frontend        | 	at com.linkedin.r2.filter.FilterChainIterator.onError(FilterChainIterator.java:101)
> datahub-frontend        | 	at com.linkedin.r2.filter.TimedNextFilter.onError(TimedNextFilter.java:48)
> datahub-frontend        | 	at com.linkedin.r2.filter.transport.ClientRequestFilter.lambda$createCallback$0(ClientRequestFilter.java:102)
> datahub-frontend        | 	at com.linkedin.r2.transport.http.common.HttpBridge$1.onResponse(HttpBridge.java:82)
> datahub-frontend        | 	at com.linkedin.r2.transport.http.client.rest.ExecutionCallback.lambda$onResponse$0(ExecutionCallback.java:64)
> datahub-frontend        | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> datahub-frontend        | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> datahub-frontend        | 	at java.lang.Thread.run(Thread.java:748)
> datahub-frontend        | Caused by: com.linkedin.r2.message.rest.RestException: Received error 500 from server for URI http://datahub-gms:8080/datasets
> datahub-frontend        | 	at com.linkedin.r2.transport.http.common.HttpBridge$1.onResponse(HttpBridge.java:76)
> datahub-frontend        | 	... 4 common frames omitted
> 
<img width="1221" alt="Screen Shot 2020-11-26 at 18 40 53" src="https://user-images.githubusercontent.com/70580659/100334501-38c8d900-3017-11eb-9183-7ebfd7523a1c.png">
<img width="1481" alt="Screen Shot 2020-11-26 at 18 41 25" src="https://user-images.githubusercontent.com/70580659/100334506-3a929c80-3017-11eb-87b5-25464028e366.png">
<img width="1262" alt="Screen Shot 2020-11-26 at 18 41 37" src="https://user-images.githubusercontent.com/70580659/100334512-3bc3c980-3017-11eb-87e3-baa40912ece2.png">

**To Reproduce**
1. clone the datahub repo
2. start ./docker/quickstart.sh
3. ingest sample data using /docker/ingestion/ingestion.sh
4. try to search for sample dataset

**Expected behavior**
sample dataset should be searchable 

**Screenshots**

**Comment by nagarjunakanamarlapudi** [comment]
I ran into the same issue yesterday. The way I fixed is, I dropped the datasetdocument elastic search index and recreated it using the settings at https://github.com/linkedin/datahub/blob/master/docker/elasticsearch-setup/dataset-index-config.json 


You could unblock yourself by doing the above. We can look into why the quickstart is not creating the index correctly for datasets.

**Comment by fr-ashikaumagiliya** [comment]
@nagarjunakanamarlapudi this fixed the exception. however,  search and DataSet browser doesnt show any records even after ingesting sample data.

**Comment by nagarjunakanamarlapudi** [comment]
@fr-ashikaumagiliya ... please truncate `metadata_aspect` table in mysql and reingest the data. Now, the data will be available both in mysql and ES, and DataHub UI will be able to show the data. 

Reason: When there is no change in data in Kv store(mysql)... the MAEs fired by ingestion process will not be used for populating search indices. In this case when u reingested the data, it is the same data .. hence MAE processor didn't populate the data into search index.

**Comment by th0ger** [comment]
Same issue here, the proposed solution doesn't work for me:

```text
docker exec -it mysql /usr/bin/mysql datahub --user=datahub --password=datahub
mysql> truncate metadata_aspect;
Query OK, 0 rows affected (0.02 sec)
```

```text
./docker/ingestion/ingestion.sh
WARNING: Native build is an experimental feature and could change at any time
WARNING: Found orphan containers (neo4j, schema-registry-ui, elasticsearch-setup, datahub-frontend, kafka-setup, schema-registry, zookeeper, datahub-gms, kafka-rest-proxy, datahub-mae-consumer, kafka-topics-ui, elasticsearch, kibana, broker, mysql, datahub-mce-consumer) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Building ingestion
[+] Building 0.4s (12/12) FINISHED
 => [internal] load .dockerignore                                                                                                                                       0.0s
 => => transferring context: 35B                                                                                                                                        0.0s
 => [internal] load build definition from Dockerfile                                                                                                                    0.0s
 => => transferring dockerfile: 38B                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/openjdk:8-jre-alpine                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/openjdk:8                                                                                                            0.0s
 => [internal] load build context                                                                                                                                       0.3s
 => => transferring context: 381.82kB                                                                                                                                   0.2s
 => [stage-1 1/3] FROM docker.io/library/openjdk:8-jre-alpine                                                                                                           0.0s
 => [builder 1/3] FROM docker.io/library/openjdk:8                                                                                                                      0.0s
 => CACHED [builder 2/3] COPY . datahub-src                                                                                                                             0.0s
 => CACHED [builder 3/3] RUN cd datahub-src && ./gradlew :metadata-ingestion-examples:mce-cli:build                                                                     0.0s
 => CACHED [stage-1 2/3] COPY --from=builder datahub-src/metadata-ingestion-examples/mce-cli/build/libs/mce-cli.jar ./                                                  0.0s
 => CACHED [stage-1 3/3] COPY --from=builder datahub-src/metadata-ingestion-examples/mce-cli/example-bootstrap.json ./                                                  0.0s
 => exporting to image                                                                                                                                                  0.0s
 => => exporting layers                                                                                                                                                 0.0s
 => => writing image sha256:c65d623b68f52956abc89f01a0536161f27bc6c76fd3b881875085a7319d7e86                                                                            0.0s
 => => naming to docker.io/library/datahub-ingestion                                                                                                                    0.0s
Successfully built c65d623b68f52956abc89f01a0536161f27bc6c76fd3b881875085a7319d7e86
Starting ingestion ... done
Attaching to ingestion
...
ingestion    |  :: Spring Boot ::        (v2.1.2.RELEASE)
ingestion    |
ingestion    | SLF4J: Class path contains multiple SLF4J bindings.
ingestion    | SLF4J: Found binding in [jar:file:/mce-cli.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
ingestion    | SLF4J: Found binding in [jar:file:/mce-cli.jar!/BOOT-INF/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
ingestion    | SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
ingestion    | SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
ingestion    | 19:30:18.096 [main] INFO  c.l.metadata.examples.cli.MceCli - Producing record 1 of 6
...
ingestion    | 19:30:18.829 [main] INFO  c.l.metadata.examples.cli.MceCli - Producing record 6 of 6
ingestion    | 19:30:18.833 [main] INFO  c.l.metadata.examples.cli.MceCli - Produced record.
ingestion exited with code 0
```
this generates logs such as:
```
...
datahub-mae-consumer    | 19:30:24.351 [mae-consumer-job-client-0-C-1] INFO  c.l.m.k.MetadataAuditEventsProcessor - {com.linkedin.metadata.snapshot.DatasetSnapshot={urn=urn:li:dataset:(urn:li:dataPlatform:hive,SampleHiveDataset,PROD), aspects=[{com.linkedin.schema.SchemaMetadata={created={actor=urn:li:corpuser:jdoe, time=1581407189000}, platformSchema={com.linkedin.schema.KafkaSchema={documentSchema={"type":"record","name":"SampleHiveSchema","namespace":"com.linkedin.dataset","doc":"Sample Hive dataset","fields":[{"name":"field_foo","type":["string"]},{"name":"field_bar","type":["boolean"]}]}}}, lastModified={actor=urn:li:corpuser:jdoe, time=1581407189000}, schemaName=SampleHiveSchema, fields=[{fieldPath=field_foo, description=Foo field description, nullable=false, type={type={com.linkedin.schema.StringType={}}}, nativeDataType=string, recursive=false}, {fieldPath=field_bar, description=Bar field description, nullable=false, type={type={com.linkedin.schema.BooleanType={}}}, nativeDataType=boolean, recursive=false}], version=0, platform=urn:li:dataPlatform:hive, hash=}}]}}
datahub-mae-consumer    | 19:30:24.373 [mae-consumer-job-client-0-C-1] INFO  c.l.m.k.MetadataAuditEventsProcessor - {com.linkedin.metadata.snapshot.DataProcessSnapshot={urn=urn:li:dataProcess:(sqoop,DEMO,PROD), aspects=[{com.linkedin.common.Ownership={owners=[{owner=urn:li:corpuser:datahub, type=DATAOWNER}], lastModified={actor=urn:li:corpuser:datahub, time=1581407189000}}}]}}
datahub-mae-consumer    | 19:30:24.613 [mae-consumer-job-client-0-C-1] INFO  c.l.m.k.MetadataAuditEventsProcessor - {com.linkedin.metadata.snapshot.DataProcessSnapshot={urn=urn:li:dataProcess:(sqoop,DEMO,PROD), aspects=[{com.linkedin.dataprocess.DataProcessInfo={outputs=[urn:li:dataset:(urn:li:dataPlatform:hbase,barSky,PROD), urn:li:dataset:(urn:li:dataPlatform:hbase,barOcean,PROD)], inputs=[urn:li:dataset:(urn:li:dataPlatform:cassandra,barEarth,DEV), urn:li:dataset:(urn:li:dataPlatform:cassandra,barMars,DEV)]}}]}}
datahub-mae-consumer    | 19:30:24.630 [I/O dispatcher 1] INFO  c.l.m.u.e.ElasticsearchConnector - Successfully feeded bulk request. Number of events: 17 Took time ms: 271
datahub-mae-consumer    | 19:30:25.447 [I/O dispatcher 1] INFO  c.l.m.u.e.ElasticsearchConnector - Successfully feeded bulk request. Number of events: 4 Took time ms: 81
```

When checking the browser for new data i still get **Elasticsearch exception - all shards failed**:
```text
datahub-gms             | 19:30:34.478 [qtp626202354-12] ERROR c.l.metadata.dao.browse.ESBrowseDAO - Browse query failed: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
datahub-frontend        | 19:30:34 [application-akka.actor.default-dispatcher-7] ERROR application - Browse failed:
datahub-frontend        | com.linkedin.restli.client.RestLiResponseException: com.linkedin.restli.client.RestLiResponseException: Response status 500, serviceErrorMessage: com.linkedin.metadata.dao.exception.ESQueryException: Browse query failed:
datahub-frontend        |       at com.linkedin.restli.internal.client.ExceptionUtil.wrapThrowable(ExceptionUtil.java:130)
...
```

**Comment by th0ger** [comment]
This latest commit still doesn't fix the issue for me.
@fr-ashikaumagiliya did it fix yours?

**Comment by jplaisted** [comment]
@th0ger are you still having issues? In #2035 truncating did work for someone.

Can you try clearing your docker volumes and starting again?

**Comment by th0ger** [comment]
Still same issue after fresh start, on latest master/commit.
I did try truncation as explained above. Not sure what you mean by recreating the index, when i follow #2035 it seems to refer back to this issue (#2014).

**Comment by jplaisted** [comment]
The easiet way to recreate the index would be to clear your docker volumes. I mean literally deleting the index so the docker scripts can create it again. Or I can try submitting a potential fix I mentioned in #2035 (update settings if the index exists)

**Comment by jjoyce0510** [comment]
@th0ger: Please let us know if this is still happening to you on the latest. 

I'd recommend a pull, ./docker/nuke.sh, and a ./docker/quickstart.sh to test.

If not, please do let us know and we can schedule some time to hop on a call to get this worked out!

**Comment by anshbansal** [comment]
Closing due to inactivity
