### ISSUE TITLE
Use 'sqlalchemy' ingestion 'doris' error

### ISSUE THREAD

**Issue by junqiangge** [datahub-project/datahub#4620]
When I use the 'Sqlalchemy' to ingest 'Doris' metadata, many unknown exceptions appear. The MySQL connection method used to parse such as decimal type fields, comment information and table attributes are abnormal

examples:

/usr/local/Lib/python3.9/site-packages/sqlalchemy/dialects/mysql/reflection.py:192: SAWarning: 
 Did not recognize type 'decimal128' of column 'total_pay_amt'

/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/reflection.py: 62 : SAWarning: Unknownschemacontent: 'COMMENT "XXX" '

**Comment by treff7es** [comment]
@kevinhu please, can you check this out?

**Comment by treff7es** [comment]
It looks like we should support `decimal128` type

**Comment by kevinhu** [comment]
Not sure what's going on with the unknown schema content warning, but this should fix the decimal128 mapping: https://github.com/datahub-project/datahub/pull/4624

**Comment by junqiangge** [comment]
I think this exception is thrown by 'Sqlalchemy'. If the decimal128 type is changed, the same error will still be thrown

**Comment by kevinhu** [comment]
It is thrown by `sqlalchemy`, but we are able to patch their type mapping this way. The warning is the same type as was raised in https://github.com/datahub-project/datahub/issues/3704

**Comment by junqiangge** [comment]
The field type can be resolved normally, but the field comment resolution still fails. Some information of the table structure, such as' distributed by hash() ',' aggregate key() ',' primary key() ',' unique key() ',' 'duplicate key()' and some table information, such as' replication '_ num','storage_ Medium 'extra value attribute

**Comment by kevinhu** [comment]
What do you mean by this?
> Some information of the table structure, such as' distributed by hash() ',' aggregate key() ',' primary key() ',' unique key() ',' 'duplicate key()' and some table information, such as' replication_num','storage_Medium' extra value attribute

**Comment by junqiangge** [comment]
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/50003929/162621419-baa84cf1-20c9-4b24-90e2-27469d160943.png">
Like this！

**Comment by junqiangge** [comment]
> 



> What do you mean by this?
> 
> > Some information of the table structure, such as' distributed by hash() ',' aggregate key() ',' primary key() ',' unique key() ',' 'duplicate key()' and some table information, such as' replication_num','storage_Medium' extra value attribute

Doris table creation statement cannot be parsed normally！
Like this : 
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/50003929/162621822-b82799f3-f8cb-4344-9b49-95c17d3a2312.png">

**Comment by kevinhu** [comment]
I see—why are you trying to ingest Doris with the MySQL connector though?

**Comment by junqiangge** [comment]
> I see—why are you trying to ingest Doris with the MySQL connector though?

OK, I see. Some Doris syntax is not supported. Thank you for your support

**Comment by MRWu4259** [comment]
麻烦问下这个问题怎么解决的？有没有现成的doris插件，可以支持抽取doris的元数据及字段描述信息
