### ISSUE TITLE
Docker quickstart can't see docker running

### ISSUE THREAD

**Issue by lenartowski** [datahub-project/datahub#6412]
**Describe the bug**
Can't start `datahub docker quickstart`, I get the message that Docker doesn't seem to be running

**To Reproduce**
run `datahub docker quickstart`

**Expected behavior**
Starting datahub

**Output**
```
~ datahub docker quickstart
Detected M1 machine
Unable to run quickstart:
- Docker doesn't seem to be running. Did you start it?
~ docker --version
Docker version 20.10.17-rd, build c2e4e01
~ docker-compose --version
Docker Compose version v2.11.1

```

**Desktop (please complete the following information):**
 - OS: Macos 12.6.1 (Macbook Pro with M2 chip)
 - Docker 20.10
 - Docker Compose v2.11.1
 - Datahub CLI version 0.9.2

**Additional context**
Docker is running as expected, e.g. `docker run hello-world` runs without problems. I have Rancher Desktop with dockerd/moby as container engine.

**Comment by aditya-radhakrishnan** [comment]
Can you check if `datahub docker check` works?

**Comment by shirshanka** [comment]
@hsheth2 : will this get fixed with your latest changes to docker cli ?

**Comment by hsheth2** [comment]
No - this PR https://github.com/datahub-project/datahub/pull/6466 solves for when older versions of docker-compose are installed.

This looks like an issue where `docker` is installed but we still can't find the docker socket file. @lenartowski I noticed that you're using Rancher desktop - do you see a `/var/run/docker.sock` file on your system? How about a `~/.rd/docker.sock` file?

Possibly related: https://github.com/rancher-sandbox/rancher-desktop/issues/2534

**Comment by aditya-radhakrishnan** [comment]
Hey @lenartowski were you able to look into Harshal's pointers? Is this still an issue for you?

**Comment by hsheth2** [comment]
@lenartowski I'm closing this for now - please reopen it if you're still facing issues with quickstart
