### ISSUE TITLE
Cannot start up/bring up container broker(kafka) service with v0.10.3 but v0.10.2

### ISSUE THREAD

**Issue by chenteddybear** [datahub-project/datahub#8133]
when installing the latest release version v0.10.3 with **sudo datahub docker quickstart --version=v0.10.3**, it couldn't not start up/bring up broker(kafka), and kept trying.

However, with version v0.10.2, it works completely fine.

**Comment by justmike1** [comment]
same issue here

**Comment by remisalmon** [comment]
Same issue, logs from docker-compose:
```
ERROR: for mysql-setup  Container "12c1454c763d" is unhealthy.

ERROR: for schema-registry  Container "c94bd37eeb26" is unhealthy.

ERROR: for kafka-setup  Container "c94bd37eeb26" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

**Comment by shirshanka** [comment]
Which host os / system is this on?

**Comment by david-leifker** [comment]
It might be helpful to move this discussion to slack. I've successfully run this version on multiple hosts using that same command, tested with both linux and m1 mac.

**Comment by chenteddybear** [comment]
Datahub envrionment:

Linux: Ubuntu 22.04.2 LTS

Client: Docker Engine - Community
 Version:           24.0.1
 API version:       1.43
 Go version:        go1.20.4

DataHub CLI version: 0.10.3
Python version: 3.10.6

**Comment by chenteddybear** [comment]
Container broker at "waiting"
<img width="296" alt="image" src="https://github.com/datahub-project/datahub/assets/33238040/009a32b5-441e-4f2a-8782-cf7962f06f9a">

Container broker at "Error"
<img width="228" alt="image" src="https://github.com/datahub-project/datahub/assets/33238040/50a07018-bcd6-4350-9dd7-3a2481ec6e8c">

**Comment by remisalmon** [comment]
On MacOS 13.3.1 with the latest Docker Deskop:

```
(venv) remisalmon@macbookpro ~/w/G/d/datahub (datahub)> docker version
Client:
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.19.5
 Git commit:        267d2e5
 Built:             Wed Jan 18 03:22:05 2023
 OS/Arch:           darwin/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.20.0 (109717)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
(venv) remisalmon@macbookpro ~/w/G/d/datahub (datahub)> datahub version
DataHub CLI version: 0.10.3.1
Python version: 3.8.16 (default, Dec 12 2022, 17:22:36)
[Clang 14.0.0 (clang-1400.0.29.202)]
(venv) remisalmon@macbookpro ~/w/G/d/datahub (datahub)> datahub docker quickstart --version=v0.10.3
[2023-06-02 14:00:18,940] INFO     {datahub.cli.quickstart_versioning:144} - Saved quickstart config to /Users/remisalmon/.datahub/quickstart/quickstart_version_mapping.yaml.
[2023-06-02 14:00:18,941] INFO     {datahub.cli.docker_cli:643} - Using quickstart plan: composefile_git_ref='v0.10.3' docker_tag='v0.10.3'
[2023-06-02 14:00:18,978] INFO     {datahub.cli.docker_cli:661} - compose file name /Users/remisalmon/.datahub/quickstart/docker-compose.yml
[2023-06-02 14:00:19,006] INFO     {datahub.cli.docker_cli:841} - Fetching docker-compose file https://raw.githubusercontent.com/datahub-project/datahub/v0.10.3/docker/quickstart/docker-compose-without-neo4j.quickstart.yml from GitHub

Pulling docker images...
This may take a while depending on your network bandwidth.
[+] Pulling 12/12
 ✔ datahub-upgrade Pulled                                                                                                                                                                                                                                  1.5s
 ✔ broker Pulled                                                                                                                                                                                                                                           1.5s
 ✔ kafka-setup Pulled                                                                                                                                                                                                                                      1.5s
 ✔ datahub-actions Pulled                                                                                                                                                                                                                                  1.5s
 ✔ zookeeper Pulled                                                                                                                                                                                                                                        1.5s
 ✔ datahub-gms Pulled                                                                                                                                                                                                                                      1.5s
 ✔ elasticsearch-setup Pulled                                                                                                                                                                                                                              1.5s
 ✔ datahub-frontend-react Pulled                                                                                                                                                                                                                           1.5s
 ✔ schema-registry Pulled                                                                                                                                                                                                                                  1.5s
 ✔ mysql Pulled                                                                                                                                                                                                                                            1.5s
 ✔ mysql-setup Pulled                                                                                                                                                                                                                                      1.5s
 ✔ elasticsearch Pulled                                                                                                                                                                                                                                    1.5s
Finished pulling docker images!

Starting up DataHub...
[+] Building 0.0s (0/0)
[+] Running 13/13
 ✔ Network datahub_network           Created                                                                                                                                                                                                               0.1s
 ✔ Container elasticsearch           Healthy                                                                                                                                                                                                               2.5s
 ✔ Container zookeeper               Healthy                                                                                                                                                                                                              11.6s
 ✔ Container mysql                   Healthy                                                                                                                                                                                                               3.6s
 ✔ Container mysql-setup             Started                                                                                                                                                                                                               3.9s
 ✔ Container elasticsearch-setup     Started                                                                                                                                                                                                               2.9s
 ✘ Container broker                  Error                                                                                                                                                                                                                21.3s
 ✔ Container schema-registry         Created                                                                                                                                                                                                               0.1s
 ✔ Container kafka-setup             Created                                                                                                                                                                                                               0.1s
 ✔ Container datahub-upgrade         Created                                                                                                                                                                                                               0.1s
 ✔ Container datahub-gms             Created                                                                                                                                                                                                               0.1s
 ✔ Container datahub-frontend-react  Created                                                                                                                                                                                                               0.1s
 ✔ Container datahub-actions         Created                                                                                                                                                                                                               0.1s
```

**Comment by pppeace** [comment]
facing same question on centos 7.5 and docker 24.0.2

=========
[2023-06-05 21:26:48,294] INFO     {datahub.cli.quickstart_versioning:144} - Saved quickstart config to /root/.datahub/quickstart/quickstart_version_mapping.yaml.
[2023-06-05 21:26:48,295] INFO     {datahub.cli.docker_cli:643} - Using quickstart plan: composefile_git_ref='master' docker_tag='head'
[2023-06-05 21:26:48,354] INFO     {datahub.cli.docker_cli:661} - compose file name /root/.datahub/quickstart/docker-compose.yml
[2023-06-05 21:26:48,380] INFO     {datahub.cli.docker_cli:841} - Fetching docker-compose file https://raw.githubusercontent.com/datahub-project/datahub/master/docker/quickstart/docker-compose-without-neo4j.quickstart.yml from GitHub

Pulling docker images... 
This may take a while depending on your network bandwidth.
[+] Pulling 12/12
 ✔ mysql-setup Pulled                                                                                                                                                                                                                                                                        3.6s 
 ✔ datahub-actions Pulled                                                                                                                                                                                                                                                                    4.0s 
 ✔ datahub-frontend-react Pulled                                                                                                                                                                                                                                                             4.8s 
 ✔ kafka-setup Pulled                                                                                                                                                                                                                                                                        2.2s 
 ✔ schema-registry Pulled                                                                                                                                                                                                                                                                    3.5s 
 ✔ zookeeper Pulled                                                                                                                                                                                                                                                                          3.0s 
 ✔ elasticsearch Pulled                                                                                                                                                                                                                                                                      3.8s 
 ✔ broker Pulled                                                                                                                                                                                                                                                                             2.8s 
 ✔ datahub-gms Pulled                                                                                                                                                                                                                                                                        3.9s 
 ✔ elasticsearch-setup Pulled                                                                                                                                                                                                                                                                4.2s 
 ✔ datahub-upgrade Pulled                                                                                                                                                                                                                                                                    3.3s 
 ✔ mysql Pulled                                                                                                                                                                                                                                                                              2.7s 
Finished pulling docker images!

Starting up DataHub...
[+] Building 0.0s (0/0)                                                                                                                                                                                                                                                                           
[+] Running 12/12
 ✔ Container mysql                   Healthy                                                                                                                                                                                                                                                 2.5s 
 ✔ Container zookeeper               Healthy                                                                                                                                                                                                                                                 6.5s 
 ✔ Container elasticsearch           Healthy                                                                                                                                                                                                                                                 2.5s 
 ✔ Container mysql-setup             Started                                                                                                                                                                                                                                                 3.1s 
 ✔ Container elasticsearch-setup     Started                                                                                                                                                                                                                                                 3.0s 
 ✘ Container broker                  Error                                                                                                                                                                                                                                                  14.2s 
 ✔ Container schema-registry         Created                                                                                                                                                                                                                                                 0.1s 
 ✔ Container kafka-setup             Created                                                                                                                                                                                                                                                 0.1s 
 ✔ Container datahub-upgrade         Created                                                                                                                                                                                                                                                 0.1s 
 ✔ Container datahub-gms             Created                                                                                                                                                                                                                                                 0.1s 
 ✔ Container datahub-frontend-react  Created                                                                                                                                                                                                                                                 0.1s 
 ✔ Container datahub-actions         Created                                                                                                                                                                                                                                                 0.1s

**Comment by pppeace** [comment]
> when installing the latest release version v0.10.3 with **sudo datahub docker quickstart --version=v0.10.3**, it couldn't not start up/bring up broker(kafka), and kept trying.
> 
> However, with version v0.10.2, it works completely fine.

@chenteddybear when I use the commond `datahub docker quickstart --version=v0.10.2`, it stucks at starting datahub-gms
![image](https://github.com/datahub-project/datahub/assets/24377710/53d63a40-d9a2-48a4-8fbe-22d0f08beae9)
as the screenshot said, it past above 6 hrs and still starting. And `docker logs datahub-gms` got nothing.
Can you or anybody help about this?  thks

**Comment by dreamofi** [comment]
I've been able to solve this by removing the previous volume of kafka container. What I've done is navigating to the docker/quickstart folder and run this command before starting:
`docker-compose -f docker-compose.quickstart.yml down -v --remove-orphans`

**Comment by chenteddybear** [comment]
**v0.10.4** works completely fine!  sudo datahub docker quickstart --version=**v0.10.4**

**Comment by hsheth2** [comment]
Checking in here - I believe these issues have been resolved in recent versions of DataHub.

We increased the timeouts for the services in the compose files, and also made the CLI more robust in that it does retries if docker hangs.

Let me know if there's still lingering issues here.

**Comment by leandro-ferreira-farm** [comment]
Have the same trouble here.

**Comment by viktorsjr** [comment]
same question on 0.10.4.3
wsl2: Ubuntu-20.04
Python version: 3.9.12
Docker version 23.0.1
![image](https://github.com/datahub-project/datahub/assets/45592344/c08e1d16-0797-4e75-bdaf-47b2709f66d4)

**Comment by leandro-ferreira-farm** [comment]
I try change the version of  Kafka image but recive the same error. 

> Have the same trouble here.
> 
> ![image](https://user-images.githubusercontent.com/127340510/253443019-89a4fdb3-b1e4-4f5c-9378-83ed3938ff33.png)

I try change the version of  Kafka image but recive the same error.

**Comment by remisalmon** [comment]
I am also still having this issue with v0.10.4 and v0.10.5 with docker-compose and the  datahub CLI.

**Comment by jyaquinas** [comment]
I'm having the same issue.

```
DataHub CLI version: 0.10.5.5
Python version: 3.9.6 (default, May  7 2023, 23:32:44) 
Docker version 20.10.17, build 100c701

Macbook M1 Ventura 13.2
```

I'm using the following command:
`datahub docker quickstart --arch m1`

```
Pulling docker images... 
This may take a while depending on your network bandwidth.
[+] Running 12/12
 ⠿ elasticsearch Pulled                                                                                                                      2.7s
 ⠿ datahub-actions Pulled                                                                                                                    2.7s
 ⠿ datahub-gms Pulled                                                                                                                        2.7s
 ⠿ zookeeper Pulled                                                                                                                          2.7s
 ⠿ schema-registry Pulled                                                                                                                    2.6s
 ⠿ elasticsearch-setup Pulled                                                                                                                2.7s
 ⠿ datahub-upgrade Pulled                                                                                                                    2.6s
 ⠿ mysql-setup Pulled                                                                                                                        2.7s
 ⠿ broker Pulled                                                                                                                             2.7s
 ⠿ kafka-setup Pulled                                                                                                                        2.7s
 ⠿ datahub-frontend-react Pulled                                                                                                             2.7s
 ⠿ mysql Pulled                                                                                                                              2.6s
Finished pulling docker images!

Starting up DataHub...
[+] Running 12/13
 ⠿ Network datahub_network           Created                                                                                                 0.0s
 ⠿ Container mysql                   Healthy                                                                                                 2.7s
 ⠿ Container zookeeper               Healthy                                                                                                 6.7s
 ⠿ Container elasticsearch           Healthy                                                                                                 2.6s
 ⠿ Container elasticsearch-setup     Started                                                                                                 2.8s
 ⠿ Container broker                  Waiting                                                                                                76.8s
 ⠿ Container mysql-setup             Started                                                                                                 2.8s
 ⠿ Container schema-registry         Created                                                                                                 0.1s
 ⠿ Container kafka-setup             Created                                                                                                 0.1s
 ⠿ Container datahub-upgrade         Created                                                                                                 0.0s
 ⠿ Container datahub-gms             Created                                                                                                 0.1s
 ⠿ Container datahub-frontend-react  Created                                                                                                 0.1s
 ⠿ Container datahub-actions         Created   
```

The broker container logs shows this:
```
[2023-08-13 12:43:35,895] INFO Cluster ID = 6tEVeZQKQ_OO8ycwfEzZYg (kafka.server.KafkaServer)
[2023-08-13 12:43:35,900] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.common.InconsistentClusterIdException: The Cluster ID 6tEVeZQKQ_OO8ycwfEzZYg doesn't match stored clusterId Some(PfTzKfGwTtGatwwocBbmhg) in meta.properties. The broker is trying to join the wrong cluster. Configured zookeeper.connect may be wrong.
        at kafka.server.KafkaServer.startup(KafkaServer.scala:234)
        at kafka.Kafka$.main(Kafka.scala:115)
        at kafka.Kafka.main(Kafka.scala)
```

**Comment by hsheth2** [comment]
@jyaquinas I suspect the volume prune and `datahub docker nuke` fixed it. I believe error happens when the broker tries to start up, writes some state to the volume, and then gets restarted by docker, so removing the previous volumes / broker state files enables it to start normally.

**Comment by YugenFring** [comment]
> I've been able to solve this by removing the previous volume of kafka container. What I've done is navigating to the docker/quickstart folder and run this command before starting: `docker-compose -f docker-compose.quickstart.yml down -v --remove-orphans`
> 
> Besides, if other containers fail and show the "xyz is unhealthy" then sometimes it may be resolved by increasing the healthcheck interval of the dependency in the quickstart docker compose files (e.g. increasing timeout to 300s, interval to 20s, retries to 30). By default the quickstart docker compose file to be used is docker-compose-without-neo4j-m1.quickstart.yml

thx, that's totally work for me!
